# First doing the imports

In [1]:
from whoosh.index import create_in
from whoosh.index import open_dir
from whoosh.fields import *
import json
import os
from tqdm import tqdm
from whoosh.query import *
from whoosh.qparser import QueryParser, FuzzyTermPlugin
import linecache
from google import genai
from pydantic import BaseModel
from typing import List

path_to_doc_chuncks = '/Users/tylergarfield/Desktop/school/CSC483/Rags_To_Searches/corpus/statpearls/chunk'

# Now we creat the index but we don't open it yet.

In [2]:
schema = Schema(doc_id = ID(stored=True), article_title = TEXT(stored=True), \
                section_title = TEXT(stored=True), content=TEXT(stored=False))

ix = create_in("woosh_index",schema)

# I want to look at the json chuncks first and perhaps do some prelinary cleanup getting the special sysmbols out of there.

In [3]:

docs_in_durr = os.listdir(path_to_doc_chuncks)

ind_writer = ix.writer()

try:

    for file in tqdm(docs_in_durr,total=len(docs_in_durr)):
    
        with open(f'{path_to_doc_chuncks}/{file}','r',encoding="utf-8") as f:
            
            for line in f:
                
                curr_art_chunk = json.loads(line)

                doc_id_curr = curr_art_chunk['id']
                cont_curr = curr_art_chunk['content']

                article_sec = curr_art_chunk['title'].split('--')
                main_title_curr = article_sec[0]
                sec_header_curr = article_sec[1]

                ind_writer.add_document(doc_id=doc_id_curr,article_title=main_title_curr,\
                                        section_title=sec_header_curr,content=cont_curr)

    ind_writer.commit()

    print("Woosh index was saved safely, let's look at this thing!")
        
except Exception as e:
    print("Owe no writing of index didn't complete successfully!❌")
    print(f"Error was: {e}")
    ind_writer.cancel()


    


100%|██████████████████████████████████████████████████████████████████████████████| 9515/9515 [01:03<00:00, 149.01it/s]


Woosh index was saved safely, let's look at this thing!


# Now that the index has been built I am going to test out querying it

In [4]:
def get_article_content(article_id):
    part_ids = article_id.split('_')
    
    main_article_id = part_ids[0]
    chunck_id = part_ids[1]

    line = linecache.getline(f'{path_to_doc_chuncks}/{main_article_id}.jsonl',(int(chunck_id)+1))
    art_json = json.loads(line)

    return art_json['content']

In [5]:
ix = open_dir("woosh_index")


with ix.searcher() as searcher:
    print(searcher.doc_count())
    parser = QueryParser("content",ix.schema)
    parser.add_plugin(FuzzyTermPlugin())

    #query_curr = parser.parse('section_title:(history AND physical)^10 AND ((headache AND backache)^0.2 OR diarhea~2^3.5 AND vomiting^2)')
    #query_curr = parser.parse('section_title:(history AND physical)^2 AND content:"headache vomiting"~1')
    query_curr = parser.parse('section_title:(history AND physical)^2 AND (content:headache~2^2 vomiting~2^2)')
    print(query_curr)
    print('\n\n')
    
    test_res = searcher.search(query_curr,limit=20)

    print("-------------Top Res Content------------")
    print(f'{test_res[0]["doc_id"]}: {get_article_content(test_res[0]["doc_id"])}\n\n')

    print("-------------Worst Res Content------------")
    print(f'{test_res[len(test_res.top_n)-1]["doc_id"]}: {get_article_content(test_res[len(test_res.top_n)-1]["doc_id"])}\n\n')


    print("-------------Possible Diseases------------")
    for res in test_res:
        print(f'\t {res.rank}) {res["article_title"]} |{res.score:.4f}|')

357680
(section_title:history^2.0 AND section_title:physical^2.0 AND content:headache~2^4.000000 AND content:vomiting~2^4.000000)



-------------Top Res Content------------
article-27743_23: The location of the tumor, supratentorial or infratentorial, is important for the manifestation of symptoms. Those with an infratentorial location usually develop hydrocephalus with headache, vomiting, irritability, and lethargy. Ataxia or other cerebellar signs and cranial nerve palsies are common. They rarely have seizures. In supratentorial locations, vomiting, seizures, and headaches are common. Hemiparesis is present if the tumor affects the cortical motor areas or the descending tracts. The presentation is also affected by age. Younger patients present irritability, vomiting, and visual problems. Those older than three years usually show headaches, vomiting, and ataxia. [8]


-------------Worst Res Content------------
article-25161_14: Patients usually present within a month of treatment wit

In [6]:
gemini_api_key = 'AIzaSyCGXeddC7iavtL5LrQuxJFyWPAsN1xzTPE'
client = genai.Client(api_key=gemini_api_key)

docs_in_durr = os.listdir(path_to_doc_chuncks)

article_names = []
disease_names = []

distinct_disease = set()

for file in tqdm(docs_in_durr,total=len(docs_in_durr)):
    
        with open(f'{path_to_doc_chuncks}/{file}','r',encoding="utf-8") as f:
            
            line = linecache.getline(f'{path_to_doc_chuncks}/{file}',1)
                
            curr_art_chunk = json.loads(line)
            article_sec = curr_art_chunk['title'].split('--')
            disease_name = article_sec[0]
            disease_name = disease_name.strip()
            
            if disease_name != "":
                article_names.append(file)
                disease_names.append(disease_name)
                distinct_disease.add(disease_name)
                


print(len(disease_names))
num_blocks = 5
increment_amt = len(disease_names)//num_blocks

start_ind = 0

class TopDiseaseLists(BaseModel):
    disease: List[str]
    num_diseases_ranked: int

dis_res = []

# Before we start this we're gonna make a map from the diseases to the ariticle titles.
disease_article_map = dict(zip(disease_names,article_names))
top_disease = []

while start_ind<len(disease_names):
    n = 100
    stop_ind_curr = start_ind+increment_amt
    
    # The professional way to structure this multi-part query:
    if len(top_disease) == 0:
        my_input = [
            # Part 1: The Instructions (System context)
            {"text": f"System: You are a medical data curator. Out of the list of diseases find the top {n} diseases. The disease at index 0 should be the most relivent the disease at index {n-1} should be the least relivent out of the top {n} most relivent diseases. Tell me how many relivent disease you output, if you can output {n} then do otherwise output however many relivent ones you can gather. Either way, tell me how many relivent results you gathered."},
            
            
            {"text": f"INPUT_DISEASE_NAMES:\n{', '.join(disease_names[start_ind:stop_ind_curr])}"},
            
        ]
    else:
        my_input = [
            # Part 1: The Instructions (System context)
            {"text": f"System: You are a medical data curator. Out of the list of diseases find the top {n} diseases. The disease at index 0 should be the most relivent the disease at index {n-1} should be the least relivent out of the top {n} most relivent diseases. Tell me how many relivent disease you output it should be {n}."},
            
            
            {"text": f"INPUT_DISEASE_NAMES:\n{', '.join(disease_names[start_ind:stop_ind_curr])}"},
            
        ]

    response = client.models.generate_content(
        model='gemini-2.5-flash',
        contents=my_input,
        config={'response_schema': TopDiseaseLists, 'response_mime_type': 'application/json','temperature': 0.1}
    )

    print(', '.join(disease_names[start_ind:stop_ind_curr]))
    print(f"Len res {response.parsed.num_diseases_ranked}")
    

    start_ind += increment_amt
    dis_res = response.parsed.disease
    break


print("Loop stoped!")
print(dis_res)

100%|█████████████████████████████████████████████████████████████████████████████| 9515/9515 [00:02<00:00, 3348.26it/s]


9515
Complex Regional Pain Syndrome, Ophthalmia Neonatorum, Fetal Movement, Paroxysmal Nocturnal Hemoglobinuria, Neuroanatomy, Corticospinal Cord Tract, Nonarteritic Anterior Ischemic Optic Neuropathy, Filariasis, Unilateral Vocal Fold Paralysis, Pick Disease, Abdominal Gunshot Wounds, Canavan Disease
Len res 5
Loop stoped!
['Paroxysmal Nocturnal Hemoglobinuria', 'Canavan Disease', 'Pick Disease', 'Complex Regional Pain Syndrome', 'Filariasis']


In [9]:
import numpy as np

In [34]:
test = np.arange(0,4).reshape(2,2)
test



array([[0, 1],
       [2, 3]])

In [36]:
np.max(test,axis=1)

array([1, 3])

In [38]:
test-np.max(test,axis=1).reshape((-1,1))

array([[-1,  0],
       [-1,  0]])